### ISSUE TITLE
Vaadin Fusion Support

### ISSUE THREAD

**Issue by sombochea** [vaadin/vaadin-gradle-plugin#117]
Hi, Vaadin Team

**Is your feature request related to a problem? Please describe.**
For my vaadin project currently using vaadin 14+ with spring boot and gradle. But I really want to use Vaadin Fusion with Gradle build too.

**Describe the solution you'd like**
I think, Gradle build is easy to build and better dependencies management.

Thank you!

**Comment by mvysny** [comment]
Hi, this plugin only caters for Vaadin 14 (and not Vaadin 19+). Since there's no Fusion in Vaadin 14 as of now, it's not possible to support it with this plugin.

It is not currently clear whether Fusion will be backported to Vaadin 14 LTS at some point in the future. Most probably not:
* It's not yet stable enough - not in shape to be backported to LTS
* It would take the team too long to do it. Even if the back-porting started, Vaadin 23 LTS would be released meanwhile, which would cause the back-porting of features to Vaadin 14 LTS to cease.

So, most probably there won't be Fusion in Vaadin 14. I'll therefore close this ticket as won't fix.

However, if there is a problem with Gradle+Fusion support for Vaadin 20+, please open a bug report at https://github.com/vaadin/flow/issues (since that's where the official Gradle plugin for Vaadin 20+ resides).

**Comment by mvysny** [comment]
Fusion will not be backported to Vaadin 14.

Quoting @Legioth 

> We will not backport Fusion because the bootstrapping changes that are needed to have a client-side app shell (e.g. client-side routing) are not backwards compatible.

> We could backport everything related to `@Enpoint` if we'd want to, but that would have quite limited value without the parts that cannot be backported.

Quoting @gilberto-torrezan 

> The first LTS version of Fusion will come with V23, and it will not be backported to V14.
