### ISSUE TITLE
vaadinBuildFrontend Task is not working with Vaadin 15 and LitElement- / TypeScript-Files

### ISSUE THREAD

**Issue by Firestorm87** [vaadin/vaadin-gradle-plugin#50]
**Desktop:**
 - OS: Windows
 - JDK version: 11
 - Gradle version: 6.2.1
 - Vaadin Plugin version: 0.5.1
 - Vaadin version: 15.0.0.rc1

**Describe the bug**
vaadinBuildFrontend Task is not working with TypeScript-Files included.
Hint: Maybe wrong generated webpack.generated.js? Its really different to previous maven-version.

ERROR in ./views/PrivacyView.ts?babel-target=es5 4:0
Module parse failed: Unexpected character '@' (4:0)
You may need an appropriate loader to handle this file type.
| import {globalCss} from "../styles/global-styles";
| 
> @customElement("privacy-view")
| export class PrivacyView extends LitElement {
| 
@ ../build/frontend/generated-flow-imports.js?babel-target=es5 72:0-39

**To Reproduce**
Setup Vaadin 15 rc1 Project with local .ts Files included.

**Comment by mvysny** [comment]
Thank you kindly :+1: there has been some changes in how Vaadin 15 does things, it's probably best to keep support for Vaadin 14 and Vaadin 15 separated. We need to discuss on the best strategy on how to do this.

**Comment by Firestorm87** [comment]
Thanks for your feedback,
Maybe you should mention this in the supported versions.
Actually the docu sounds like vaadin 15 should be supported:
- "official Vaadin Gradle Plugin for Vaadin 14 **and newer**."
- "Vaadin 14 Compatibility mode is not supported"

**Comment by mstahv** [comment]
cc: @vlukashov

**Comment by mvysny** [comment]
@Firestorm87 you're right, the readme change is in PR https://github.com/vaadin/vaadin-gradle-plugin/pull/51

**Comment by dcracauer** [comment]
Also interested in this, since I don't use maven. 

I forked the repo and did my best to port over the current maven logic.  Code is here: https://github.com/dcracauer/vaadin-gradle-plugin/tree/feature/vaadin-15

It is working for me locally on a very simple project. There are tests failing in MiscSingleModuleTest because gradle is reporting 'UP_TO_DATE' instead of 'SUCCESS'. I can't reproduce it with a real project.

**Comment by mvysny** [comment]
@dcracauer thank you so much, that's awesome job! Could you please keep the code around until we figure out what versioning scheme would be the best to have?

**Comment by dcracauer** [comment]
> @dcracauer thank you so much, that's awesome job! Could you please keep the code around until we figure out what versioning scheme would be the best to have?

No problem at all. I'll leave it around as long as you need.

**Comment by Firestorm87** [comment]
Any further timelines for vaadin 15 support?

**Comment by mvysny** [comment]
@Firestorm87 unfortunately no estimate yet. First we need to agree with @mstahv what is the best strategy to have two or three different plugin versions simultaneously (since plugin for Vaadin 15 differs a bit from Vaadin 14's version, both code-wise and dependency-wise). Generally I see two options:

1. separate git branches: master for newest Vaadin, plus a branch for every Vaadin release, which means branches for V14.1, V14.2, V15, V16 and master for V17.
2. two separate plugins in one git codebase as individual Gradle modules. 

@mstahv mentioned though that Vaadin 15 version is currently not a priority.

**Comment by mvysny** [comment]
Since Vaadin 15 is no longer supported, we will not add support for it. However, support for Vaadin 17 is being pushed into master as we speak, so you will be able to use the plugin with Vaadin 17.
