### ISSUE TITLE
[Doc] Improve documentation and clarify if gradle is supposed to be working equally good as maven with vaadin

### ISSUE THREAD

**Issue by masbaehr** [vaadin/vaadin-gradle-plugin#53]
Hi, i feel the documentation of the gradle plugin is lacking and the development seems to be quite inactive. How is this project supposed to go on? Just asking if i should migrate to maven or not. (I started with gradle from the beginning (without plugin) as i think the build.gradle file is much more readable than maven pom.

Just a sidenode:

./gradlew clean build -Pvaadin.productionMode

does not seem to work

**Comment by mvysny** [comment]
Hi! Apologies, I had notifications turned off for this project :) I will try my best to maintain this project as well as I can.

Could you please pinpoint the issue with the documentation? I can then update the docs and add the missing parts.

This plugin should support basic stuff (development and production mode with NPM) equally as good as the Maven plugin. However, there are parts which are omitted for now: the migration from older Vaadin versions for example; also there is no support for old Bower mode. However, if you stick with npm and Vaadin 14, the plugin should be able to support you just fine.

Regarding the `./gradlew clean build -Pvaadin.productionMode` not working - could you please tell me in more detail what's wrong? It seems to be working for me just fine on the example project; maybe it's just the matter of missing documentation rather than a missing functionality.

**Comment by masbaehr** [comment]
Thanks for answering! As for the error - this seemed to be a Windows Powershell issue, and thus can be ignored. With the regular command prompt it works

![image](https://user-images.githubusercontent.com/38694044/78135136-ab9a9980-7421-11ea-97ec-42d072c291dc.png)

As for the docs it would be useful to add more specifics about Spring boot - but this probably would go to https://github.com/vaadin/base-starter-spring-gradle  (e.g. how to use Jetty or Undertow instead of Tomcat which is default). Or how to run debugging and develop with other IDE other than IntelliJ especially VSCode or Eclipse, Ultimate - as much as i like it is paid. For example I'm using VSCode with Gradle Plugins

Actually i don't remember everything i noted, if it should come to mind i will post it here ;)

**Comment by mvysny** [comment]
Hi!

> this seemed to be a Windows Powershell issue

Understood, thanks! Yet, still it would be good to document on how to escape the command properly. I'm not a Windows user, I wonder whether something like `./gradlew clean build "-Pvaadin.productionMode"` would help :thinking: 

> how to use Jetty or Undertow instead of Tomcat which is default

I do not use Spring myself, so I'm just guessing here, but maybe it's just the case of removing the Tomcat dependency and adding the Jetty plugin as documented at https://docs.spring.io/spring-boot/docs/1.5.10.RELEASE/reference/html/howto-embedded-servlet-containers.html#howto-use-jetty-instead-of-tomcat

> how to run debugging and develop with other IDE other than IntelliJ especially VSCode or Eclipse

Gotcha. With Spring, I think you can simply run or debug the Application.java class since it contains the main method. That way you can debug easily without any special support from the IDE - so you can easily use Intellij Community. If you're not using Spring, you can take a look at https://github.com/mvysny/vaadin14-embedded-jetty-gradle - it embeds Jetty and introduces a class with the main method, but without the need of using Spring.

Unfortunately I'm not familiar with Eclipse nor VSCode, so I can't help you there. However, please feel free to modify the documentation and create a PR. However, it is true that we should provide a documentation listing all of the abovementioned possibilities.

**Comment by mvysny** [comment]
> Just asking if i should migrate to maven or not. 

If you prefer Gradle, then you should definitely stay with Gradle. Even though the current status of the Vaadin Gradle Plugin is "experimental", Vaadin plans to offer an official support for Gradle in the future (by marking this plugin as "official" and therefore including it into the "official" fold, with proper maintenance and everything).

@masbaehr please let me know if there are any further questions or suggestions - if not, I propose to close this bug report since I feel that all questions have been answered.

**Comment by mvysny** [comment]
> how to run debugging and develop with other IDE other than IntelliJ especially VSCode or Eclipse

There's a known issue with Eclipse and VSCode. Eclipse+BuildShip may need a workaround in order for this project to work, please see https://vaadin.com/forum/thread/18241436 for more info. This applies to Visual Studio Code as well since it also uses Eclipse bits and BuildShip underneath - see https://github.com/mvysny/vaadin14-embedded-jetty-gradle/issues/4 for more details.

**Comment by mvysny** [comment]
Closing this ticket since there are no further open questions.
