### ISSUE TITLE
vaadinBuildFrontend seems to hang

### ISSUE THREAD

**Issue by mcooper7290** [vaadin/vaadin-gradle-plugin#59]
**Desktop (please complete the following information):**
 - OS: Windows
 - JDK version: 8
 - Gradle version: 6.3
 - Vaadin Plugin version: 0.6.0

**Describe the bug**
When I run "gralde vaadinBuildFrontend" the process never finishes.  I have a small test project which is posted here:
https://vaadin.com/forum/thread/18241436

I have left the process running for as long as 30 minutes.
No errors are produced.

**To Reproduce**
Grab sample project from above posting.
Run "gradle vaadinBuildFrontEnd"

**Expected behavior**
Should complete within a few minutes or produce error messages and exit.

**Screenshots**

**Additional context**

**Comment by mvysny** [comment]
I tried to run `gradle vaadinBuildFrontend` myself, with Gradle 6.3, and it took about 1m 30s to run that goal. So, the task worked for me, I can not unfortunately reproduce the issue.

The thing is that during the execution of the `vaadinBuildFrontend` task, npm is downloading lots of packages from the internet. If the internet connectivity is slow, then the gradle process may look stalled since there is no visible CPU nor disk activity. It could also be caused by npm repository being down or highly congested.

Could you please try again, perhaps now the networking issue could be corrected and the build would pass?

**Comment by mcooper7290** [comment]
It is working now for me as well.  Must have been some network or npm server issue.  Thanks for the explanation.  That will help me track down the problem if it happens again.
